"""Add AuditLogs

Revision ID: 2a5569b9882f
Revises: 8eebb0ccfb81
Create Date: 2025-12-26 11:38:54.614644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5569b9882f'
down_revision = '8eebb0ccfb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resource_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('resource',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.alter_column('resource',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('details')
        batch_op.drop_column('resource_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
